//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.App_Data
{
    
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// EF测试表
    /// </summary>
    public partial class T_EF_DEMO
    {
        /// <summary>
        /// id
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string NAME { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public string SEX { get; set; }
        /// <summary>
        /// 年龄
        /// </summary>
        public decimal AGE { get; set; }
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime TIME { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        public string TEXT { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        public string PHONE { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string EMAIL { get; set; }
        /// <summary>
        /// 部门
        /// </summary>
        public string DEPT { get; set; }
    }
}
